### ISSUE TITLE
Add support for extracting comments associated with parameter ports and signal ports.

### ISSUE THREAD

**Issue by DaveMcEwan** [DaveMcEwan/svdata#41]

**Comment by vasilissoti** [comment]
This issue can be closed.

**Comment by DaveMcEwan** [comment]
I'll leave it open until #54 (or its replacement) is merged.

**Comment by vasilissoti** [comment]
> I'll leave it open until #54 (or its replacement) is merged.

Just added the replacement PR (#55).
