### ISSUE TITLE
Add support for comments inside modules

### ISSUE THREAD

**Issue by prokie** [DaveMcEwan/svdata#71]
Hello!

I have been using this package for a while at work, and now I finally have time to contribute. At work we use this to create documentation for our Systemverilog modules.  We usually put a docstring inside the module, but with the `svdata` today there is no way to parse that.

So I would like to add comments to SvModuleDeclaration
```rust
pub struct SvModuleDeclaration {
    pub identifier: String,
    pub parameters: Vec<SvParameter>,
    pub ports: Vec<SvPort>,
    pub instances: Vec<SvInstance>,
    pub filepath: String,
    pub comments: Vec<String>,  // All the comments under a module declaration header
}
```
and modify `module_declaration_ansi` to parse the comments.

If you think this is a good idea, I will be happy to create a pull request.

**Comment by DaveMcEwan** [comment]
Sounds good to me :)

**Comment by prokie** [comment]
Closing this issue since we #72 was merged to the main branch.
